---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: dctwin
type: Opaque
stringData:
  POSTGRES_USER: dctwin
  POSTGRES_PASSWORD: CHANGE_ME_IN_PRODUCTION
  POSTGRES_DB: dctwin
